name: Override
on: push
env:
    FOO: bar
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${FOO}"
            - env:
                FOO: baz
              run: echo "${FOO}"