name: Test
on: 
    pull_request:
        paths: ['go/**/*.go']

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Setup Go lang
              uses: actions/setup-go@v5
              with:
                  go-version: '1.22'
            - name: Run Test
              run: go test go/excellent/*.go